<a href="https://colab.research.google.com/github/infotovikas/Learn-Python/blob/main/beginner/Basic%20To%20Advanced%20Arrays%20in%20Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Using the array module in Python**

In [1]:
#Example 1: Creating an Array

import array
# Create an array of integers
arr = array.array('i', [1, 2, 3, 4, 5])
print(f"Array: {arr}")

Array: array('i', [1, 2, 3, 4, 5])


In [2]:
#Example 2: Accessing Array Elements

import array
# Create an array of integers
arr = array.array('i', [10, 20, 30, 40, 50])

# Access elements by index
print(f"Element at index 2: {arr[2]}")  # Access element at index 2
print(f"Last element: {arr[-1]}")  # Access last element

Element at index 2: 30
Last element: 50


In [3]:

#Example 3: Adding and Removing Elements

import array
# Create an array of integers
arr = array.array('i', [1, 2, 3, 4, 5])

# Append an element to the array
arr.append(6)
print(f"Array after append: {arr}")

# Insert an element at a specific position
arr.insert(2, 10)
print(f"Array after insert: {arr}")

# Remove an element
arr.remove(3)
print(f"Array after remove: {arr}")

Array after append: array('i', [1, 2, 3, 4, 5, 6])
Array after insert: array('i', [1, 2, 10, 3, 4, 5, 6])
Array after remove: array('i', [1, 2, 10, 4, 5, 6])


In [4]:
#Example 4: Array Traversal

import array
# Create an array of integers
arr = array.array('i', [1, 2, 3, 4, 5])

# Traverse the array using a for loop
print("Traversing array:")
for element in arr:
    print(element)

Traversing array:
1
2
3
4
5


**2. Using NumPy Arrays**
: NumPy is widely used for array manipulations and mathematical operations in Python.

First, install NumPy if it's not already installed:

In [5]:
!pip install numpy

In [6]:
#Example 1: Creating a NumPy Array

import numpy as np
# Create a NumPy array from a Python list
arr = np.array([10, 20, 30, 40, 50])
print(f"NumPy Array: {arr}")

NumPy Array: [10 20 30 40 50]


In [7]:
#Example 2: Accessing Elements of a NumPy Array

import numpy as np
# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access elements by index
print(f"Element at index 2: {arr[2]}")  # Access element at index 2
print(f"Last element: {arr[-1]}")  # Access last element

Element at index 2: 30
Last element: 50


In [8]:
#Example 3: Array Operations in NumPy

import numpy as np
# Create two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Perform element-wise addition
result = arr1 + arr2
print(f"Addition of arr1 and arr2: {result}")

# Perform element-wise multiplication
result = arr1 * arr2
print(f"Multiplication of arr1 and arr2: {result}")

Addition of arr1 and arr2: [5 7 9]
Multiplication of arr1 and arr2: [ 4 10 18]


In [9]:
#Example 4: Array Slicing

import numpy as np
# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Slice the array to get elements from index 2 to 5
slice_arr = arr[2:6]
print(f"Sliced Array (index 2 to 5): {slice_arr}")

Sliced Array (index 2 to 5): [30 40 50 60]


In [10]:
#Example 5: Reshaping a NumPy Array

import numpy as np
# Create a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape the array into 2D (2 rows, 4 columns)
reshaped_arr = arr.reshape(2, 4)
print(f"Reshaped Array (2x4):\n{reshaped_arr}")

Reshaped Array (2x4):
[[1 2 3 4]
 [5 6 7 8]]


In [11]:
#Example 6: Array Broadcasting

import numpy as np
# Create a 2D NumPy array
arr = np.array([[1, 2], [3, 4]])

# Broadcast scalar to the array (adding 5 to each element)
result = arr + 5
print(f"Array after broadcasting (add 5):\n{result}")

Array after broadcasting (add 5):
[[6 7]
 [8 9]]


In [12]:
#Example 7: NumPy Array Operations on Multi-dimensional Arrays

import numpy as np
# Create a 2D NumPy array (Matrix)
matrix = np.array([[1, 2], [3, 4]])

# Transpose the matrix
transposed_matrix = np.transpose(matrix)
print(f"Transposed Matrix:\n{transposed_matrix}")

# Matrix multiplication (dot product)
dot_product = np.dot(matrix, transposed_matrix)
print(f"Dot product of matrix and its transpose:\n{dot_product}")

Transposed Matrix:
[[1 3]
 [2 4]]
Dot product of matrix and its transpose:
[[ 5 11]
 [11 25]]


**3. Working with Multidimensional Arrays**

In [13]:
#Example 1: Creating a 2D Array with NumPy

import numpy as np
# Create a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D NumPy Array:\n{arr}")

2D NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#Example 2: Accessing Elements in a 2D Array

import numpy as np
# Create a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access a specific element
print(f"Element at [1, 2]: {arr[1, 2]}")  # Element in row 1, column 2

# Slice a submatrix
submatrix = arr[0:2, 1:3]
print(f"Sliced Submatrix:\n{submatrix}")

Element at [1, 2]: 6
Sliced Submatrix:
[[2 3]
 [5 6]]


**4. Array Manipulation in NumPy**

In [15]:
#Example: Stacking Arrays

import numpy as np
# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack arrays vertically (row-wise)
stacked_arr = np.vstack((arr1, arr2))
print(f"Vertically Stacked Array:\n{stacked_arr}")

# Stack arrays horizontally (column-wise)
stacked_arr_h = np.hstack((arr1, arr2))
print(f"Horizontally Stacked Array: {stacked_arr_h}")

Vertically Stacked Array:
[[1 2 3]
 [4 5 6]]
Horizontally Stacked Array: [1 2 3 4 5 6]


**5. Multi-dimensional Array Indexing and Slicing**

In [16]:


#Example: Indexing and Slicing in 3D Arrays

import numpy as np
# Create a 3D NumPy array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Access a specific element
print(f"Element at [1, 1, 0]: {arr[1, 1, 0]}")

# Slice the array
sliced_arr = arr[:, 1, :]
print(f"Sliced Array (first column of each 2x2 block):\n{sliced_arr}")

Element at [1, 1, 0]: 7
Sliced Array (first column of each 2x2 block):
[[3 4]
 [7 8]]
